const { exit, printErr } = require('../exit');
exit('测试的错误1')
printErr('测试的错误2')